name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-lastest
    steps:
      - name: Prict greeting
        run: echo "Hello  World"
      - name: Print goodbye
        run: echo "Good bye!"
